export const settings = {
  dots: true,
  infinite: true,
  speed: 2000,
  slidesToShow: 5,
  slidesToScroll: 1,
  swipeToSlide: true,
  centerPadding: "1px",
  arrows: false,
  cssEase: "linear",
  responsive: [
    {
      breakpoint: 1024,
      settings: {
        dots: true,
        infinite: true,
        speed: 2000,
        slidesToShow: 5,
        slidesToScroll: 1,
        swipeToSlide: true,
        centerPadding: "1px",
        arrows: false,
        cssEase: "linear",
      },
    },
    {
      breakpoint: 600,
      settings: {
        dots: true,
        infinite: true,
        speed: 2000,
        slidesToShow: 3,
        slidesToScroll: 1,
        swipeToSlide: true,
        centerPadding: "1px",
        arrows: false,
        cssEase: "linear",
      },
    },
    {
      breakpoint: 480,
      settings: {
        dots: true,
        infinite: true,
        speed: 2000,
        slidesToShow: 2,
        slidesToScroll: 1,
        swipeToSlide: true,
        centerPadding: "1px",
        arrows: false,
        cssEase: "linear",
      },
    },
  ],
};
